version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - store_artifacts:
          path: coverage
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm run build
          name: Build Maka
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - 'prisma'
      - build:
          requires:
            - test

