version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - store_artifacts:
          path: coverage
      - run:
          command: npm build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
